config/routes.rb
Rails.application.routes.draw do

  get 'levels/index'

  devise_for :users

  root to: "dasboard#index"
  resources :students
  resources :parents
  resources :levels
  resources :types
  resources :teachers
  resources :attendances
  resources :key_events
  resources :events
  get 'batch_action_parent' => 'parents#batch_action_parent'
  get 'check_parent_number' => 'parents#check_parent_number'
  get 'student_status' => 'students#student_status'
  get 'event_calender' => 'calendars#event_calender'
  get 'get_event_details' => 'calendars#get_event_details'

end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  include TypesHelper
  include FormHelper
  require 'will_paginate/array'

  skip_before_action :verify_authenticity_token, :only => [:destroy]
  before_action :find_type, only: [:show, :edit,:update,:destroy]

  def index
    if request.xhr? && params[:q].present?
      type_filter
    else
      @types = Type.paginate(:page => params[:page], :per_page => 10)
    end
    add_breadcrumb "Types", types_path
  end

  def show
    add_breadcrumb "Types", types_path
  end

  def new
    @type = Type.new
  end

  def edit;end

  def create
    @type = Type.new(type_params)
    if @type.save
      flash[:notice] = "Type created successfully"
      redirect_to types_path
    else
      render 'new'
    end
  end

  def update
    @type.update(type_params)
    flash[:notice] = "Type updated successfully"
    redirect_to type_path
  end

  def destroy
    @type.destroy
    redirect_to types_path
  end

  private

  def find_type
    @type = Type.find(params[:id])
  end

  def type_params
    params.require(:type).permit(:name, :description, :fee, :payment_terms,:user_id)
  end

end

app/helpers/types_helper.rb
module TypesHelper

  def payment_terms
    [
      ['Monthly', 'monthly'],
      ['Quarterly','quarterly'],
      ['Half-Yearly','half-yearly'],
      ['Yearly','yearly']
    ]
  end

  # For filter type name
  def type_name
    [
      ['Contains','contain'],
      ['Equals','equals'],
      ['Starts with','start_with'],
      ['Ends with','end_with']
    ]

  end

  # For fee filter and students count
  def fee_filter
    [
      ['Equal','equal'],
      ['Greater than','greater_than'],
      ['Less than','less_than']
    ]

  end

  # Filter method
  def type_filter
    if params[:q].present?
      count = 0
      query_array = []
      query = ""
      if params[:name].present?
        if params[:q][:name_contains] == "contain"
          count = count + 1
          query += " name like ? "
          query_array << "%#{params[:name]}%"
        elsif params[:q][:name_contains] == "equals"
          count = count + 1
          query += " name = ? "
          query_array << params[:name]

        elsif params[:q][:name_contains] == "start_with"
          count = count + 1
          query += " name LIKE ? "
          query_array << "#{params[:name]}%"
        elsif params[:q][:name_contains] == "end_with"
          count = count + 1
          query += " name LIKE ? "
          query_array << "%#{params[:name]}"
        end
      end
      if count > 0 && params[:fee].present?
        if params[:q][:fee_contains] == "equal"
          query += " AND fee = ? "
          query_array << params[:fee]
        elsif params[:q][:fee_contains] == "greater_than"
          query += " AND fee > ? "
          query_array << params[:fee]
        elsif params[:q][:fee_contains] == "less_than"
          query += " AND fee < ? "
          query_array << params[:fee]
        end
      elsif params[:fee].present?
        if params[:q][:fee_contains] == "equal"
          query += " fee = ? "
          query_array << params[:fee]
        elsif params[:q][:fee_contains] == "greater_than"
          query += " fee > ? "
          query_array << params[:fee]
        elsif params[:q][:fee_contains] == "less_than"
          query += " fee < ? "
          query_array << params[:fee]
        end
      end
      if count > 0 && params[:students_count].present?
        if params[:q][:students_count_contains] == "equal"
          query += " AND students_count = ? "
          query_array << params[:students_count]
        elsif params[:q][:students_count_contains] == "greater_than"
          query += " AND students_count > ? "
          query_array << params[:students_count]
        elsif params[:q][:students_count_contains] == "less_than"
          query += " AND students_count < ? "
          query_array << params[:students_count]
        end
      elsif params[:students_count].present?
        if params[:q][:students_count_contains] == "equal"
          query += " students_count = ? "
          query_array << params[:students_count]
        elsif params[:q][:students_count_contains] == "greater_than"
          query += " students_count > ? "
          query_array << params[:students_count]
        elsif params[:q][:students_count_contains] == "less_than"
          query += " students_count < ? "
          query_array << params[:students_count]
        end
      end
      if count > 0 && params[:payment_terms].present?
        query += " AND payment_terms = ? "
        query_array << params[:payment_terms]
      elsif params[:payment_terms].present?
        query += " payment_terms = ? "
        query_array << params[:payment_terms]
      end
      full_query = query_array.unshift(query)
      @types = Type.where(full_query).paginate(:page => params[:page], :per_page => 10)
      @ids = @types.collect(&:id)
      if full_query == [""]
        return @types
      end
    else
    end
  end
end

app/views/types/_add_type.html.erb
<div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">Add New Student</h4>
        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form class="form-horizontal">
          <fieldset>
            <div class="form-group row">
              <label class="col-xl-3 col-form-label">First Name</label>
              <div class="col-xl-8">
                <input class="form-control" type="text" placeholder="First Name">
              </div>
            </div>
          </fieldset>
          <fieldset>
            <div class="form-group row">
              <label class="col-xl-3 col-form-label">Last Name</label>
              <div class="col-xl-8">
                <input class="form-control" type="text" placeholder="Last Name">
              </div>
            </div>
          </fieldset>
          <fieldset>
            <div class="form-group row">
              <label class="col-xl-3 col-form-label">D.O.B</label>
              <div class="col-xl-8">
                <input class="form-control" type="date" placeholder="D.O.B">
              </div>
            </div>
          </fieldset>
          <fieldset>
            <div class="form-group row">
              <label class="col-xl-3 col-form-label">Gender</label>
              <div class="col-xl-8">
                <select class="custom-select custom-select-md">
                  <option selected="">Select Gender</option>
                  <option value="1">Male</option>
                  <option value="2">Female</option>
                </select>
              </div>
            </div>
          </fieldset>
          <fieldset>
            <div class="form-group row">
              <label class="col-xl-3 col-form-label"></label>
              <div class="col-xl-8">
                <button class="btn btn-labeled btn-success mb-2" type="button" id= "swal-demo5">
                <span class="btn-label"><i class="fa fa-plus" ></i></span>Add Another Student
                </button>
              </div>
            </div>
          </fieldset>
          <!-- This section will only show once they have clicked the Add Another Student button. Admin fills in the form and if they need to add another student they will click on that button and this section will show added students. Students will be saved once clicked on save -->
          <fieldset>
            <div class="form-group row">
              <label class="col-xl-3 col-form-label">Students</label>
              <div class="col-xl-8">
                <b>Waqas Ahmad, Test Student</b>
                <p> You must click Save to save the Students</p>
              </div>
            </div>
          </fieldset>
        </form>
      </div>
      <div class="modal-footer card-footer">
        <button class="btn btn-danger" type="button" data-dismiss="modal">Close</button>
        <button class="btn btn-primary" type="button">Save</button>
      </div>
    </div>
  </div>

app/views/types/_email_model_popup.html.erb
<div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="emailModalLabel">Send Email</h4>
        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form class="form-horizontal">
          <fieldset>
            <div class="form-group row">
              <label class="col-xl-3 col-form-label">Subject</label>
              <div class="col-xl-8">
                <input class="form-control" type="text" placeholder="Subject">
              </div>
            </div>
          </fieldset>
          <fieldset>
            <div class="form-group row">
              <label class="col-xl-3 col-form-label">Message</label>
              <div class="col-xl-8">
                <textarea class="form-control" rows="5"></textarea>
              </div>
            </div>
          </fieldset>
          <fieldset>
            <div class="form-group row">
              <label class="col-xl-3 col-form-label"><em class="fa fa-info-circle"></em></label>
              <div class="col-xl-8">
                <p> An email will be sent to the parents of the students in this classroom.</p>
              </div>
            </div>
          </fieldset>
        </form>
      </div>
      <div class="modal-footer card-footer">
        <button class="btn btn-danger" type="button" data-dismiss="modal">Close</button>
        <button class="btn btn-primary" type="button">Send</button>
      </div>
    </div>
  </div>

app/views/types/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="card card-default">
      <div class="card-header">Type Form</div>
        <div class="card-body">
          <%= form_for @type do |f| %>
            <%= form_group_for f, :name, label: false  do %>
              <div class="form-group">
                <label>Name*</label>
                <%= f.text_field :name ,class: "form-control", placeholder: "Please enter name"%>
              </div>
            <%end%>
            <div class="form-group">
              <label>Description</label>
              <%= f.text_area :description ,class: "form-control", placeholder: "Please enter description"%>
            </div>
            <%= form_group_for f, :fee, label: false  do %>
              <div class="form-group">
                <label>Fee*</label>
                <%= f.text_field :fee ,class: "form-control", placeholder: "Please enter fee"%>
              </div>
            <% end %>
            <%= form_group_for f, :payment_terms, label: false  do %>
              <div class="form-group">
                <label>Payment Terms*</label>
                <%= f.select :payment_terms ,options_for_select(payment_terms, selected: f.object.payment_terms),{prompt: 'Select Payment terms'}, class: "chosen-select form-control" %>
              </div>
            <% end %>
            <%= f.submit :submit, class: "btn btn-sm btn-primary"%>
            <%= link_to 'Cancel', types_path,class: "btn btn-sm btn-warning" %>
          <% end %>
        </div>
    </div>
  </div>
</div>

app/views/types/_type_filter.html.erb
<%= form_tag '/types' ,method: :get,remote: true do%>
  <table class="table bb table-striped filter-table">
    <tbody>
      <tr>
        <td colspan="2">
          <label class="col-form-label"> Name </label>
        </td>
      </tr>
      <tr>
        <td width="50%">
          <div class="form-group">
            <%= select_tag "q[name_contains]", options_for_select(type_name),class: "chosen-select form-control"%>
          </div>
        </td>
        <td>
          <div class="form-group">
            <%= text_field_tag 'name' ,params[:name],class: " form-control "%>
          </div>
        </td>
      </tr>
      <tr>
        <td colspan="2">
          <label class="col-form-label">Fee</label>
        </td>
      </tr>
      <tr>
        <td width="50%">
          <div class="form-group">
            <%= select_tag "q[fee_contains]", options_for_select(fee_filter),class: "chosen-select form-control"%>
          </div>
        </td>
        <td>
          <div class="form-group">
            <%= text_field_tag 'fee' ,params[:fee],class: " form-control "%>
          </div>
        </td>
      </tr>
      <tr>
        <td colspan="2">
          <label class="col-form-label">Payment Terms</label>
        </td>
      </tr>
      <tr>
        <td colspan="2">
          <div class="form-group">
            <%= select_tag "payment_terms", options_for_select([nil]+payment_terms),class: "chosen-select form-control"%>
          </div>
        </td>
      </tr>
      <tr>
        <td colspan="2">
          <label class="col-form-label">Students Count</label>
        </td>
      </tr>
      <tr>
        <td width="50%">
          <div class="form-group">
            <%= select_tag "q[students_count_contains]", options_for_select(fee_filter),class: "chosen-select form-control"%>
          </div>
        </td>
        <td>
          <div class="form-group">
            <%= text_field_tag 'students_count' ,params[:students_count],class: " form-control "%>
          </div>
        </td>
      </tr>
      <tr>
        <td>
          <div class="form-group">
            <%= submit_tag 'Filter',class: "btn btn-sm btn-primary", id: "filter_type_list"%>
          </div>
        </td>
        <td>
          <div>
          <%= link_to 'Clear filter', types_path,class: "btn btn-sm btn-warning", id: "type_clear-filter" %>
          </div>
        </td>
      </tr>
    </tbody>
  </table>
<%end%>

<style type="text/css">
  .filter-table td{
    padding: 5px;
  }
  .filter-table td .form-group{
    margin-bottom: 0;
  }
  #type_clear-filter{
    margin-left: -100px;
  }
</style>

app/views/types/_type_list.html.erb
<% unless @types.blank? %>
  <div class="table-responsive">
    <table class="table table-bordered table-striped table-hover" id="table-ext-3">
      <thead>
        <th data-check-all>
          <div class="checkbox c-checkbox" data-toggle="tooltip" data-title="Check All">
            <label>
            <input type="checkbox" name = type_arr1[] value="<%= @types.ids %>" class="check_box_selection" id="type_main_checkbox" >
            <span class="fa fa-check"></span>
            </label>
          </div>
        </th>
        <th>Name</th>
        <th>Description</th>
        <th>Fee</th>
        <th>Payment Terms</th>
        <th>Count</th>
        <th>Actions</th>
      </thead>
      <tbody>
        <% @types.order('created_at DESC').each do |type|%>
          <tr>
            <td>
              <div class="checkbox c-checkbox">
                <label>
                <input type="checkbox" name = type_arr[] value="<%= type.id %>" id ="type_check_box">
                <span class="fa fa-check"></span>
                </label>
              </div>
            </td>
            <td><%=link_to "#{type.name}",type_path(type.id)%></td>
            <td>
              <%= type.description %>
            </td>
            <td>£<%= type.fee %></td>
            <td><%= type.payment_terms %></td>
            <td><%= type.students_count %></td>
            <td>
              <div class="btn-group">
                <button class="btn btn-primary" type="button"><span class="fa fa-cog"></span></button>
                <button class="btn dropdown-toggle btn-primary" type="button" data-toggle="dropdown">
                <span class="sr-only">primary</span>
                </button>
                <div class="dropdown-menu animated" role="menu">
                  <%= link_to 'View',type_path(type.id),class: "dropdown-item"%>
                  <%= link_to 'Edit',edit_type_path(type.id),class: "dropdown-item"%>
                  <%= hidden_field_tag :d_type, type.id %>
                  <a href="JavaScript:void(0);" class= "dropdown-item swal-demo8">Delete</a>
                </div>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="pagination-link">
    <%= js_will_paginate @types %>
  </div>
<% else %>
  <p class="no_record_found">No Type Found</p>
<% end %>

app/views/types/edit.html.erb
<div class="wrapper">
  <%= render 'layouts/header'%>
  <%= render 'layouts/left_sidebar'%>
  <%= render 'layouts/right_sidebar'%>
  <section class="section-container">
    <div class="content-wrapper">
      <div class="content-heading">
        <div>Edit Type
        </div>
      </div>
      <%= render 'form'%>
    </div>
  </section>
</div>

app/views/types/index.html.erb
<link rel="stylesheet" href="/assets/theme_css/sweetalert/sweetalert.css">
<div class="wrapper">
  <%= render 'layouts/header'%>
  <%= render 'layouts/left_sidebar'%>
  <%= render 'layouts/right_sidebar'%>
  <section class="section-container">
    <div class="content-wrapper">
      <div class="content-heading">
        <div>
          Types
          <ol class="breadcrumb breadcrumb px-0 pb-0">
            <li class="breadcrumb-item">
              <a href="/types"><%= render_breadcrumbs :separator => ' / ' %></a>
            </li>
          </ol>
        </div>
        <div class="ml-auto">
          <%= link_to(new_type_path,class: 'btn btn-labeled btn-success mb-2') do %>
          <span class="btn-label"><i class="fa fa-plus"></i></span>New Type
          <% end %>
        </div>
      </div>
      <div class="row">
        <div class="col-xl-2">
          <div class="ml-auto">
            <div class="input-group float-right">
              <div class="desktop-view">
                <select class="custom-select" id="type_batch" disabled = "true">
                  <option value="0">Bulk action</option>
                  <option value="2">Delete</option>
                </select>
              </div>
            </div>
          </div>
        </div>
      </div>
      <br />
      <div class="row">
        <div class="col-xl-4 hide-on-desktop">
          <div class="card card-default">
            <div class="card-body">
              <p class="lead">Filters</p>
              <%= render 'type_filter'%>
            </div>
          </div>
        </div>
        <div class="mobile-view">
          <select class="custom-select" id="type_batch" disabled = "true">
            <option value="0">Bulk action</option>
            <option value="2">Delete</option>
          </select>
        </div>
        <div class="col-xl-8">
          <div class="card card-default">
            <div id="type_list_table">
              <%= render 'type_list'%>
           </div>
          </div>
        </div>
        <div class="col-xl-4 hide-on-mobile">
          <div class="card card-default">
            <div class="card-body">
              <p class="lead">Filters</p>
              <%= render 'type_filter'%>
            </div>
          </div>
        </div>
      </div>
  </section>
  <%= render '/layouts/footer'%>
</div>
<script src="/assets/theme_js/sweetalert/sweetalert.min.js"></script>
<script src="/assets/theme_js/js/app.js"></script>

app/views/types/index.js.erb
$("#type_list_table").html("<%=j render('type_list', types: @types)%>")
// $('.pagination a').attr('data-remote', 'true');

app/views/types/new.html.erb
<div class="wrapper">
  <%= render 'layouts/header'%>
  <%= render 'layouts/left_sidebar'%>
  <%= render 'layouts/right_sidebar'%>
  <section class="section-container">
    <div class="content-wrapper">
      <div class="content-heading">
        <div>Create New Type
        </div>
      </div>
      <%= render 'form'%>
    </div>
  </section>
</div>

app/views/types/show.html.erb
<link rel="stylesheet" href="/assets/theme_css/sweetalert/sweetalert.css">
<div class="wrapper">
  <%= render 'layouts/header'%>
  <%= render 'layouts/left_sidebar'%>
  <%= render 'layouts/right_sidebar'%>
  <section class="section-container">
    <div class="content-wrapper">
      <div class="content-heading">
        <div>
          <%= @type.name %>
          <ol class="breadcrumb breadcrumb px-0 pb-0">
            <li class="breadcrumb-item">
              <%= render_breadcrumbs :separator => ' / '%>
            </li>
            <li class="breadcrumb-item active"><%=@type.name%></li>
          </ol>
        </div>
        <div class="ml-auto">
          <button class="btn btn-labeled btn-danger mb-2 swal-demo8" type="button">
            <%= hidden_field_tag :d_type, @type.id %>
            <span class="btn-label"><i class="fa fa-trash-alt" ></i></span>Delete
          </button>
          <%= link_to(edit_type_path(@type.id),class: 'btn btn-labeled btn-warning mb-2') do %>
            <span class="btn-label"><i class="fa fa-pencil-alt"></i></span>Edit
          <% end %>
        </div>
      </div>
      <!-- </div> -->
      <div class="row">
        <div class="col-lg-4">
          <div class="card card-default">
            <div class="card-body">
              <p>Metrics</p>
              <div class="row text-center">
                <div class="col-3 col-lg-6 col-xl-3">
                  <div class="inline my-2"> <%= pie_chart @type.students.group(:gender).count,width: "70px", height: "70px",legend: false %></div>
                  <p class="mt-3">Gender</p>
                </div>
                <div class="col-3 col-lg-6 col-xl-3">
                  <div class="inline my-2"> <%= pie_chart @type.students.group(:ethnicity_group).count,width: "70px", height: "70px",legend: false,id: "ethnicity_chart" %></div>
                  <p class="mt-3">Ethinicity</p>
                </div>
              </div>
            </div>
            <table class="table bb">
              <tbody>
                <tr>
                  <td>
                    <strong>Descripition</strong>
                  </td>
                  <td><%= @type.description %></td>
                </tr>
                <tr>
                  <td>
                    <strong>Fee</strong>
                  </td>
                  <td><%= @type.fee %></td>
                </tr>
                <tr>
                  <td>
                    <strong>Payment Terms</strong>
                  </td>
                  <td><%= @type.payment_terms %></td>
                </tr>
                <tr>
                  <td>
                    <strong>Created at</strong>
                  </td>
                  <td><%= @type.created_at.strftime('%d %B,%Y') %></td>
                </tr>
              </tbody>
            </table>
            <div class="card-footer">
              <% diff = (Time.now.to_i - @type.updated_at.to_i) %>
              <div class="text-sm text-muted">Last updated at <%= distance_of_time_in_words(diff).split("and")[0].chomp(', ') %></div>
            </div>
          </div>
          <!-- end Aside card-->
        </div>
        <div class="col-lg-8">
          <div class="mb-3 d-flex">
            <div>
              <span data-toggle="modal" data-target="#myModal">
              <button class="btn btn-sm btn-secondary" title="Add New Student" type="button" data-toggle="tooltip">
              <em class="fa fa-user-plus"></em>
              </button>
              </span>
              <button class="btn btn-sm btn-secondary" title="Print Students List" type="button" data-toggle="tooltip">
              <em class="fa fa-print"></em>
              </button>
              <span data-toggle="modal" data-target="#emailModal">
              <button class="btn btn-sm btn-secondary" title="Send email" type="button" data-toggle="tooltip">
              <em class="fa fa-envelope"></em>
              </button>
              </span>
            </div>
            <div class="ml-auto">
              <p class="mb-0 mt-1"><%= @type.students.count%></p>
            </div>
          </div>
          <div class="card b">
            <div class="card-body">
              <table class="table w-100" id="datatable12" >
                <thead>
                  <tr>
                    <th>Student Name</th>
                    <th>Student Type</th>
                    <th>Status</th>
                    <th>fee</th>
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  <% @type.students.each do |student| %>
                    <tr>
                      <td>
                        <%= student.name %>
                      </td>
                      <td>
                        <%if student.type_id.present? && student.status == "Enrolled" %>
                          <%= Type.find(student.type_id).name %>
                        <% end %>
                      </td>
                      <td>
                        <button class="mb-1 btn btn-success" type="button"><%= student.status%></button>
                      </td>
                      <td>£<%= student.type.fee %></td>
                      <td>
                        <div class="btn-group">
                          <button class="btn btn-primary" type="button"><span class="fa fa-cog"></span></button>
                          <button class="btn dropdown-toggle btn-primary" type="button" data-toggle="dropdown">
                          <span class="sr-only">primary</span>
                          </button>
                          <div class="dropdown-menu animated " role="menu">
                            <%= link_to 'View',student_path(student.id),class: "dropdown-item"%>
                            <%= link_to 'Edit',edit_student_path(student.id),class: "dropdown-item"%>
                            <%= hidden_field_tag :d_student, student.id%>
                            <a href="JavaScript:void(0);" class= "dropdown-item swal-demo7">Delete</a>
                          </div>
                        </div>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <%= render '/layouts/footer'%>
</div>

<script src="/assets/theme_js/sweetalert/sweetalert.min.js"></script>
<script src="/assets/theme_js/js/app.js"></script>

<!-- Add Student Modal-->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <%= render 'add_type' %>
</div>
<!-- Email Modal-->
<div class="modal fade" id="emailModal" tabindex="-1" role="dialog" aria-labelledby="emailModalLabel" aria-hidden="true">
  <%= render 'email_model_popup'%>
</div>