config/routes.rb
Rails.application.routes.draw do

  get 'levels/index'

  devise_for :users

  root to: "dasboard#index"
  resources :students
  resources :parents
  resources :levels
  resources :types
  resources :teachers
  resources :attendances
  resources :key_events
  resources :events
  get 'batch_action_parent' => 'parents#batch_action_parent'
  get 'check_parent_number' => 'parents#check_parent_number'
  get 'student_status' => 'students#student_status'
  get 'event_calender' => 'calendars#event_calender'
  get 'get_event_details' => 'calendars#get_event_details'

end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  has_one :level
  has_many :rewards
  has_many :messages
  has_many :contains
  has_many :wages, :dependent => :destroy
  has_and_belongs_to_many :messages

  # Validations
  validates :name, :presence =>{message: "Name can't be empty"}
  validates :contact, :presence =>{message: "Contact can't be empty"}
  validates :email, :presence =>{message: "Email can't be empty"}

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  include TeachersHelper
  include FormHelper

  skip_before_action :verify_authenticity_token, :only => [:destroy]
  before_action :find_teacher, only: [:show, :edit,:update,:destroy]

  def index
    if request.xhr? && params[:q].present?
      teacher_filter
    else
      @teachers = Teacher.all
    end
    add_breadcrumb "Teachers", teachers_path
  end

  def show
    add_breadcrumb "Teachers", teachers_path
  end

  def new
    @teacher = Teacher.new
  end

  def edit;end

  def create
    @teacher =  Teacher.new(teacher_params)
    if @teacher.save
      flash[:notice] = "Teacher created successfully"
      redirect_to teachers_path
    else
      render 'new'
    end
  end

  def update
    @teacher.update(teacher_params)
    flash[:notice] = "Teacher updated successfully"
    redirect_to teacher_path
  end

  def destroy
    @teacher.destroy
    redirect_to teachers_path
  end

  private

  def find_teacher
    @teacher = Teacher.find(params[:id])
  end

  def teacher_params
    params.require(:teacher).permit(:name, :address, :postcode, :contact, :email, :user_id, :active, :crb_checked, :crb_checked_on, :deleted_at, :dbs_ref, :emergencyno_1, :emergencyno_2, :emergencyno_3, :is_disabled, :special_needs, :specialneeds_notes, :disabilities_note, :doctors_name,:employee_number, :start_date, :job_title, :nationality, :NI_number, :salary, :working_hours, :marital_status, :gender, :contract_type, :dob, :leaving_date, :city)
  end

end

app/helpers/teachers_helper.rb
module TeachersHelper

  # For filter teacher dropdown
  def filter_teacher_dropdown
    [
      ['Contains','contain'],
      ['Equals','equals'],
      ['Starts with','start_with'],
      ['Ends with','end_with']
    ]

  end

  # Teacher filter method
  def teacher_filter
    if params[:q].present?
      count = 0
      query_array = []
      query = ""
      if params[:name].present?
        if params[:q][:name_contains] == "contain"
          count = count + 1
          query += " name like ? "
          query_array << "%#{params[:name]}%"
        elsif params[:q][:name_contains] == "equals"
          count = count + 1
          query += " name = ? "
          query_array << params[:name]

        elsif params[:q][:name_contains] == "start_with"
          count = count + 1
          query += " name LIKE ? "
          query_array << "#{params[:name]}%"
        elsif params[:q][:name_contains] == "end_with"
          count = count + 1
          query += " name LIKE ? "
          query_array << "%#{params[:name]}"
        end
      end
      if count > 0 && params[:email].present?
        if params[:q][:email_contains] == "contain"
          query += " AND email like ? "
          query_array << "%#{params[:email]}%"
        elsif params[:q][:email_contains] == "equals"
          query += " AND email = ? "
          query_array << params[:email]
        elsif params[:q][:email_contains] == "start_with"
          query += " AND email like ? "
          query_array << "#{params[:email]}%"
        elsif params[:q][:email_contains] == "end_with"
          query += " AND email like ? "
          query_array << "%#{params[:email]}"
        end
      elsif params[:email].present?
        if params[:q][:email_contains] == "contain"
          query += " email like ? "
          query_array << "%#{params[:email]}%"
        elsif params[:q][:email_contains] == "equals"
          query += " email = ? "
          query_array << params[:email]
        elsif params[:q][:email_contains] == "start_with"
          query += " email like ? "
          query_array << "#{params[:email]}%"
        elsif params[:q][:email_contains] == "end_with"
          query += " email like ? "
          query_array << "%#{params[:email]}"
        end
      end
      if count > 0 && params[:crb_checked].present?
        query += " AND crb_checked = ? "
        if  params[:crb_checked] == "true"
        query_array << true
        else
          query_array << false
        end
      elsif params[:crb_checked].present?
        query += " crb_checked = ? "
        if  params[:crb_checked] == "true"
        query_array << true
        else
          query_array << false
        end
      end
      if count > 0 && params[:employee_number].present?
        if params[:q][:employee_number_contains] == "contain"
          query += " AND employee_number like ? "
          query_array << "%#{params[:employee_number]}%"
        elsif params[:q][:employee_number_contains] == "equals"
          query += " AND employee_number = ? "
          query_array << params[:employee_number]
        elsif params[:q][:employee_number_contains] == "start_with"
          query += " AND employee_number like ? "
          query_array << "#{params[:employee_number]}%"
        elsif params[:q][:employee_number_contains] == "end_with"
          query += " AND employee_number like ? "
          query_array << "%#{params[:employee_number]}"
        end
      elsif params[:employee_number].present?
        if params[:q][:employee_number_contains] == "contain"
          query += " employee_number like ? "
          query_array << "%#{params[:employee_number]}%"
        elsif params[:q][:employee_number_contains] == "equals"
          query += " employee_number = ? "
          query_array << params[:employee_number]
        elsif params[:q][:employee_number_contains] == "start_with"
          query += " employee_number like ? "
          query_array << "#{params[:employee_number]}%"
        elsif params[:q][:employee_number_contains] == "end_with"
          query += " employee_number like ? "
          query_array << "%#{params[:employee_number]}"
        end
      end
      if count > 0 && params[:contract_type].present?
        query += " AND contract_type = ? "
        query_array << params[:contract_type]
      elsif params[:contract_type].present?
        query += " contract_type = ? "
        query_array << params[:contract_type]
      end
      full_query = query_array.unshift(query)
      @teachers = Teacher.where(full_query)
      @ids = @teachers.collect(&:id)
      if full_query == [""]
        return @teachers
      end
    else
    end
  end
end

app/views/teachers/_employment_details.html.erb
<table class="table table-striped">
  <tbody>
    <tr>
      <td>
        <label class="col-form-label"> Contract Type:</label>
      </td>
      <td>
        <div class="form-group">
          <%= @teacher.contract_type %>
        </div>
      </td>
    </tr>
    <tr>
      <td>
        <label class="col-form-label">Employee Number:</label>
      </td>
      <td>
        <div class="form-group">
          <%= @teacher.employee_number %>
        </div>
      </td>
    </tr>
    <tr>
      <td>
        <label class="col-form-label">Start Date:</label>
      </td>
      <td>
        <div class="form-group">
          <%= @teacher.start_date %>
        </div>
      </td>
    </tr>
    <tr>
      <td>
        <label class="col-form-label">Leaving Date:</label>
      </td>
      <td>
        <div class="form-group">
          <%= @teacher.leaving_date %>
        </div>
      </td>
    </tr>
    <tr>
      <td>
        <label class="col-form-label">Job Title:</label>
      </td>
      <td>
        <div class="form-group">
          <%= @teacher.job_title %>
        </div>
      </td>
    </tr>
    <tr>
      <td>
        <label class="col-form-label">Nationality:</label>
      </td>
      <td>
        <div class="form-group">
          <%= @teacher.nationality %>
        </div>
      </td>
    </tr>
    <tr>
      <td>
        <label class="col-form-label">NI Number:</label>
      </td>
      <td>
        <div class="form-group">
          <%= @teacher.NI_number %>
        </div>
      </td>
    </tr>
    <tr>
      <td>
        <label class="col-form-label">Salary:</label>
      </td>
      <td>
        <div class="form-group">
          <%= @teacher.salary %>
        </div>
      </td>
    </tr>
    <tr>
      <td>
        <label class="col-form-label">Working Hours:</label>
      </td>
      <td>
        <div class="form-group">
          <%= @teacher.working_hours %>
        </div>
      </td>
    </tr>
    <tr>
      <td>
        <label class="col-form-label">Marital Status:</label>
      </td>
      <td>
        <div class="form-group">
          <%= @teacher.marital_status %>
        </div>
      </td>
    </tr>
  </tbody>
</table>

app/views/teachers/_filter_teacher.html.erb
<%= form_tag '/teachers' ,method: :get,remote: true do%>
  <table class="table bb table-striped filter-table">
    <tbody>
      <tr>
        <td colspan="2">
          <label class="col-form-label">Name</label>
        </td>
      </tr>
      <tr>
        <td width="50%">
          <div class="form-group">
            <%= select_tag "q[name_contains]", options_for_select(filter_teacher_dropdown),class: "chosen-select form-control"%>
          </div>
        </td>
        <td>
          <div class="form-group">
            <%= text_field_tag 'name' ,params[:name],class: " form-control "%>
          </div>
        </td>
      </tr>
      <tr>
        <td colspan="2">
          <label class="col-form-label">Email</label>
        </td>
      </tr>
      <tr>
        <td width="50%">
          <div class="form-group">
            <%= select_tag "q[email_contains]", options_for_select(filter_teacher_dropdown),class: "chosen-select form-control"%>
          </div>
        </td>
        <td>
          <div class="form-group">
            <%= text_field_tag 'email' ,params[:email],class: " form-control "%>
          </div>
        </td>
      </tr>
      <tr>
        <td colspan="2">
          <label class="col-form-label">DBS Checked</label>
        </td>
      </tr>
      <tr>
        <td colspan="2">
          <div class="form-group">
            <%= select_tag :crb_checked, options_for_select([[nil],['Yes',true],['No',false]]),class: "chosen-select form-control"%>
          </div>
        </td>
      </tr>
      <tr>
        <td colspan="2">
          <label class="col-form-label">Employee Number</label>
        </td>
      </tr>
      <tr>
        <td width="50%">
          <div class="form-group">
            <%= select_tag "q[employee_number_contains]", options_for_select(filter_teacher_dropdown),class: "chosen-select form-control"%>
          </div>
        </td>
        <td>
          <div class="form-group">
            <%= text_field_tag 'employee_number' ,params[:employee_number],class: " form-control "%>
          </div>
        </td>
      </tr>
      <tr>
        <td colspan="2">
          <label class="col-form-label">Contract Type</label>
        </td>
      </tr>
      <tr>
        <td colspan="2">
          <div class="form-group">
            <%= select_tag "contract_type",options_for_select([[nil],["Full Time","full time"], ["Part time", "part time"], ["Fixed-term", "fixed-term"], ["Zero hours", "zero hours"]]) ,class: "chosen-select form-control"%>
          </div>
        </td>
      </tr>
      <tr>
        <td>
          <div class="form-group">
            <%= submit_tag 'Filter',class: "btn btn-sm btn-primary", id: "filter_student_list"%>
          </div>
        </td>
        <td>
          <div>
          <%= link_to 'Clear filter', teachers_path,class: "btn btn-sm btn-warning", id: "clear-teacher-filter" %>
          </div>
        </td>
      </tr>
    </tbody>
  </table>
<%end%>

<style type="text/css">
  .filter-table td{
    padding: 5px;
  }
  .filter-table td .form-group{
    margin-bottom: 0;
  }
  #clear-teacher-filter{
    margin-left: -100px;
  }
</style>

app/views/teachers/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="card card-default">
      <div class="card-header">Teacher Form</div>
      <div class="card-body">
        <%= form_for @teacher do |f|%>
          <div class="bg-gray-lighter px-3 py-2 my-3"><h6>Teacher Details</h6></div>
          <div class="form-section">
            <%= form_group_for f, :name, label: false  do %>
              <div class="form-group">
                <label>Name*</label>
                <%= f.text_field :name ,class: "form-control", placeholder: "Please enter name"%>
              </div>
            <%end%>
            <div class="form-group">
              <label>Address</label>
              <%= f.text_field :address,class: "form-control", placeholder: "Please enter address" %>
            </div>
            <div class="form-group">
              <label>City</label>
              <%= f.text_field :city,class: "form-control", placeholder: "Please enter city" %>
            </div>
            <div class="form-group">
              <label>Postcode</label>
              <%= f.text_field :postcode,class: "form-control", placeholder: "Please enter postcode" %>
            </div>
            <%= form_group_for f, :contact, label: false  do %>
              <div class="form-group">
                <label>Contact*</label>
                <%= f.text_field :contact,class: "form-control", placeholder: "Please enter contact number" %>
              </div>
            <% end %>
            <%= form_group_for f, :email, label: false  do %>
              <div class="form-group">
                <label>Email*</label>
                <%= f.text_field :email,class: "form-control", placeholder: "Please enter email" %>
              </div>
            <% end %>
            <div class="form-group">
              <label>Date Of Birth</label>
              <%= f.date_field :dob,class: "form-control" %>
            </div>
            <div class="form-group">
              <label>Gender</label>
              <%= f.select :gender,([["Female","female"], ["Male", "male"]]),{prompt: 'Select Gender'}, { :class => 'form-control' } %>
            </div>
            <div class="form-check">
              <%= f.check_box :crb_checked,class: "form-check-input"  %>
              <label class="form-check-label">DBS checked</label>
            </div>
            <div class="form-group">
              <label>If yes, please specify</label>
              <%= f.date_field :crb_checked_on,class: "form-control", placeholder: "PleaseEnter the date DBS checked on" %>
            </div>
            <div class="form-group">
              <label>DBS Ref</label>
              <%= f.text_field :dbs_ref ,class: "form-control", placeholder: "Please enter DBS ref number"%>
            </div>
          </div>
          <div class="bg-gray-lighter px-3 py-2 my-3"><h6>Medical Details</h6></div>
          <div class="form-section">
            <div class="form-group">
              <label>Doctor's Name</label>
              <%= f.text_field :doctors_name,class: "form-control", placeholder: "Please enter name of teacher GP" %>
            </div>
            <div class="form-check">
              <%= f.check_box :is_disabled,class: "form-check-input"  %>
              <label class="form-check-label">Does the teacher have Disabilities?</label>
            </div>
            <div class="form-group">
              <label>If yes, please specify</label>
              <%= f.text_area :disabilities_note,class: "form-control", placeholder: "Please enter disabilities note here" %>
            </div>
            <div class="form-check">
              <%= f.check_box :special_needs,class: "form-check-input"  %>
              <label class="form-check-label">Does the teacher have any Special teaching/medical needs?</label>
            </div>
            <div class="form-group">
              <label>If yes, please specify</label>
              <%= f.text_area :specialneeds_notes,class: "form-control", placeholder: "Please enter specialneeds note here" %>
            </div>
          </div>
          <div class="bg-gray-lighter px-3 py-2 my-3"><h6>Emergency Contact Details</h6></div>
          <div class="form-section">
            <div class="form-group">
              <label>Emergency number 1</label>
              <%= f.text_field :emergencyno_1,class: "form-control", placeholder: "Please enter emergency number 1" %>
            </div>
            <div class="form-group">
              <label>Emergency number 2</label>
              <%= f.text_field :emergencyno_2,class: "form-control", placeholder: "Please enter emergency number 2" %>
            </div>
            <div class="form-group">
              <label>Emergency number 3</label>
              <%= f.text_field :emergencyno_3,class: "form-control", placeholder: "Please enter emergency number 3" %>
            </div>
          </div>
          <div class="bg-gray-lighter px-3 py-2 my-3"><h6>Employment Details</h6></div>
          <div class="form-section">
            <div class="form-group">
              <label>Type of contract</label>
              <%= f.select :contract_type,([["Full Time","full time"], ["Part time", "part time"], ["Fixed-term", "fixed-term"], ["Zero hours", "zero hours"]]),{prompt: 'Select contract type'}, { :class => 'form-control' } %>
            </div>
            <div class="form-group">
              <label>Employee Number</label>
              <%= f.text_field :employee_number,class: "form-control", placeholder: "Please enter employee number" %>
            </div>
            <div class="form-group">
              <label>Start Date</label>
              <%= f.date_field :start_date,class: "form-control" %>
            </div>
            <div class="form-group">
              <label>Leaving Date</label>
              <%= f.date_field :leaving_date,class: "form-control" %>
            </div>
            <div class="form-group">
              <label>Job Title</label>
              <%= f.text_field :job_title,class: "form-control", placeholder: "Please enter job titile e.g. Arabic Teacher" %>
            </div>
            <div class="form-group">
              <label>Nationality</label>
              <%= f.text_field :nationality,class: "form-control", placeholder: "Please enter nationality" %>
            </div>
            <div class="form-group">
              <label>Ni Number</label>
              <%= f.text_field :NI_number,class: "form-control", placeholder: "Please enter national insurance number" %>
            </div>
            <div class="form-group">
              <label>Salary</label>
              <%= f.number_field :salary,class: "form-control", placeholder: "Please enter employee yearly salary e.g. 15000" %>
            </div>
            <div class="form-group">
              <label>Working Hours</label>
              <%= f.number_field :working_hours,class: "form-control", placeholder: "Please enter weekly working hours" %>
            </div>
            <div class="form-group">
              <label>Marital Status</label>
              <%= f.text_field :marital_status,class: "form-control", placeholder: "Please enter marital status e.g. Married, Single" %>
            </div>
          </div>
          <div class="form-group">
            <%= f.submit :submit, class: "btn btn-sm btn-primary"%>
            <% if params[:action] == 'edit' %>
              <%= link_to 'Cancel', teacher_path(@teacher),class: "btn btn-sm btn-warning" %>
            <% else %>
              <%= link_to 'Cancel', teachers_path,class: "btn btn-sm btn-warning" %>
            <% end %>
          </div>
        <%end%>
      </div>
    </div>
  </div>
</div>
<style type="text/css">
  .form-section{
    padding: 0 25px;
  }
</style>

app/views/teachers/_registration_details.html.erb
<table class="table table-striped">
  <tbody>
    <tr>
      <td>
        <label class="col-form-label">DBS Check:</label>
      </td>
      <td>
        <div class="form-group">
          <% if @teacher.crb_checked == true %>
            <div>Yes</div>
          <%else%>
            <div>No</div>
          <% end %>
        </div>
      </td>
    </tr>
    <tr>
      <td>
        <label class="col-form-label">DBS checked on:</label>
      </td>
      <td>
        <div class="form-group">
          <%= @teacher.crb_checked_on %>
        </div>
      </td>
    </tr>
    <tr>
      <td>
        <label class="col-form-label">DBS ref number:</label>
      </td>
      <td>
        <div class="form-group">
          <%= @teacher.dbs_ref %>
        </div>
      </td>
    </tr>
  </tbody>
</table>

app/views/teachers/_teacher_list.html.erb
<% unless @teachers.blank? %>
  <table class="table w-100 table-striped " id="datatable1">
    <thead>
      <tr>
      <th data-check-all style="padding: 0.75rem">
        <div class="checkbox c-checkbox" data-toggle="tooltip" data-title="Check All" >
          <label>
          <input type="checkbox" name = parent_arr1[] value="<%= @teachers.ids %>" class="check_box_selection" id="teacher_main_checkbox" >
          <span class="fa fa-check"></span>
          </label>
        </div>
        </th>
        <th>Name</th>
        <th>Contact</th>
        <th>Email</th>
        <th>Gender</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @teachers.each do |teacher|%>
        <tr>
          <td>
            <div class="checkbox c-checkbox table-check">
              <label>
              <input type="checkbox" name = teacher_arr[] value="<%= teacher.id %>" id="teacher_check_selection">
              <span class="fa fa-check"></span>
              </label>
            </div>
          </td>
          <td><%=link_to "#{teacher.name}",teacher_path(teacher.id)%></td>
          <td><%= teacher.contact %></td>
          <td><%= teacher.email %></td>
          <td><%= teacher.gender%></td>
          <td>
            <div class="btn-group">
              <button class="btn btn-primary" type="button"><span class="fa fa-cog"></span></button>
              <button class="btn dropdown-toggle btn-primary" type="button" data-toggle="dropdown">
              <span class="sr-only">primary</span>
              </button>
              <div class="dropdown-menu" role="menu">
                <%= link_to 'View',teacher_path(teacher.id),class: "dropdown-item"%>
                <%= link_to 'Edit',edit_teacher_path(teacher.id),class: "dropdown-item"%>
                <%= hidden_field_tag :d_teacher, teacher.id %>
                <a href="JavaScript:void(0);" class= "dropdown-item swal-demo9">Delete</a>
              </div>
            </div>
          </td>
        </tr>
      <%end%>
    </tbody>
  </table>
<% else %>
  <p class="no_record_found">No Teacher Found</p>
<% end %>

app/views/teachers/index.html.erb
<link rel="stylesheet" href="/assets/theme_css/sweetalert/sweetalert.css">
<div class="wrapper">
  <%= render 'layouts/header'%>
  <%= render 'layouts/left_sidebar'%>
  <%= render 'layouts/right_sidebar'%>
  <section class="section-container">
    <div class="content-wrapper">
      <div class="content-heading">
        <div>
          Teachers
          <ol class="breadcrumb breadcrumb px-0 pb-0">
            <li class="breadcrumb-item">
              <a href="/levels"><%= render_breadcrumbs :separator => ' / ' %></a>
            </li>
          </ol>
        </div>
        <div class="ml-auto">
          <%= link_to(new_teacher_path,class: 'btn btn-labeled btn-success mb-2') do %>
             <span class="btn-label"><i class="fa fa-plus"></i></span>New Teacher
          <% end %>
          <button class="btn btn-labeled btn-primary mb-2" type="button">
          <span class="btn-label"><i class="fa fa-upload"></i></span>Import Teachers</button>
        </div>
      </div>
      <div class="row">
        <div class="col-xl-2">
          <div class="ml-auto">
            <div class="input-group float-right">
              <div class="desktop-view">
                <select class="custom-select" id="teacher_batch" disabled="true">
                  <option value="0">Bulk action</option>
                  <option value="1">Delete</option>
                  <option value="2">Clone</option>
                  <option value="3">Export</option>
                </select>
              </div>
            </div>
          </div>
        </div>
      </div>
      <br />
      <div class="row">
        <div class="col-xl-4 hide-on-desktop">
          <div class="card card-default">
            <div class="card-body">
              <p class="lead">Filters</p>
              <%= render 'filter_teacher'%>
            </div>
          </div>
        </div>
        <div class="mobile-view">
          <select class="custom-select" id="teacher_batch" disabled="true">
            <option value="0">Bulk action</option>
            <option value="1">Delete</option>
            <option value="2">Clone</option>
            <option value="3">Export</option>
          </select>
        </div>
        <div class="col-xl-8">
          <div class="card b">
            <div class="card-body">
              <div id = "teacher_list_table">
                <%= render 'teacher_list' %>
              </div>
            </div>
          </div>
        </div>
        <div class="col-xl-4 hide-on-mobile">
          <div class="card card-default">
            <div class="card-body">
              <p class="lead">Filters</p>
              <%= render 'filter_teacher'%>
            </div>
          </div>
        </div>
      </div>
  </section>
  <%= render '/layouts/footer'%>
</div>
<script src="/assets/theme_js/sweetalert/sweetalert.min.js"></script>
<script src="/assets/theme_js/js/app.js"></script>

app/views/teachers/index.js.erb
$("#teacher_list_table").html("<%=j render('teacher_list', teachers: @teachers)%>")

app/views/teachers/show.html.erb
<link rel="stylesheet" href="/assets/theme_css/sweetalert/sweetalert.css">
<div class="wrapper">
  <%= render 'layouts/header'%>
  <%= render 'layouts/left_sidebar'%>
  <%= render 'layouts/right_sidebar'%>
  <section class="section-container">
    <div class="content-wrapper">
      <div class="content-heading">
        <div>
          <%= @teacher.name %>
          <ol class="breadcrumb breadcrumb px-0 pb-0">
            <li class="breadcrumb-item">
              <a href="/levels"><%= render_breadcrumbs :separator => ' / ' %></a>
            </li>
            <li class="breadcrumb-item active"><%= @teacher.name %></li>
          </ol>
        </div>
        <div class="ml-auto">
          <button class="btn btn-labeled btn-danger mb-2 swal-demo9" type="button">
          <%= hidden_field_tag :d_teacher, @teacher.id %>
          <span class="btn-label"><i class="fa fa-trash-alt" ></i></span>Delete
          </button>
          <%= link_to(edit_teacher_path(@teacher.id),class: 'btn btn-labeled btn-warning mb-2') do %>
          <span class="btn-label"><i class="fa fa-pencil-alt"></i></span>Edit
          <% end %>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-4">
          <div class="card card-default">
            <div class="card-body bb text-center">
              <div class="py-4">
                <img class="img-fluid rounded-circle img-thumbnail thumb96" src="/assets/user/02.jpeg" alt="Contact">
              </div>
            </div>
              <%= render 'teacher_details' %>
            <div class="card-footer">
              <% diff = (Time.now.to_i - @teacher.updated_at.to_i) %>
              <div class="text-sm text-muted">Last updated at <%= distance_of_time_in_words(diff).split("and")[0].chomp(', ') %>
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-8">
          <div id="accordion">
            <div class="card card-default mb-1">
              <div class="card-header" id="headingOne">
                <div class="d-flex justify-content-end">
                  <div class="btn-group">
                    <button class="btn btn-link" data-toggle="dropdown">
                    <em class="fa fa-ellipsis-v fa-lg text-muted"></em>
                    </button>
                    <div class="dropdown-menu dropdown-menu-right-forced animated fadeInLeft" role="menu">
                      <a class="dropdown-item" href="#">
                      <span>Send by message</span>
                      </a>
                      <a class="dropdown-item" href="#">
                      <span>Share contact</span>
                      </a>
                      <a class="dropdown-item" data-toggle="modal" data-target="#emergencyModal1" href="#">
                      <span>View Emergency Details</span>
                      </a>
                      <a class="dropdown-item" href="#">
                      <span class="text-warning">Delete contact</span>
                      </a>
                    </div>
                  </div>
                </div>
                <h4 class="mb-0">
                  <a class="text-inherit" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne" href="">Employment Details</a>
                </h4>
              </div>
              <div class="collapse show" id="collapseOne" aria-labelledby="headingOne" data-parent="#accordion">
                <div class="card-body border-top">
                  <%= render 'employment_details.html.erb'%>
                </div>
              </div>
            </div>
          </div>
          <div class="card card-default mb-1">
            <div class="card-header" id="headingTwo">
              <h4 class="mb-0">
                <a class="text-inherit collapsed" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo" href="">Registration Details</a>
              </h4>
            </div>
            <div class="collapse show" id="collapseTwo" aria-labelledby="headingTwo" data-parent="#accordion">
              <div class="card-body border-top">
                <%= render 'registration_details'%>
              </div>
            </div>
          </div>
          <div class="card card-default mb-1">
            <div class="card-header" id="headingTwo">
              <h4 class="mb-0">
                <a class="text-inherit collapsed" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo" href="">Medical Details</a>
              </h4>
            </div>
            <div class="collapse show" id="collapseTwo" aria-labelledby="headingTwo" data-parent="#accordion">
              <div class="card-body border-top">
                <%= render 'medical_details'%>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <%= render '/layouts/footer'%>
</div>
<script src="/assets/theme_js/sweetalert/sweetalert.min.js"></script>
<script src="/assets/theme_js/js/app.js"></script>

<!-- Model popup -->
<div class="modal fade" id="emergencyModal1" tabindex="-1" role="dialog" aria-labelledby="emergencyModalLabel" aria-hidden="true">
  <%= render 'model_popup' %>
</div>