config/routes.rb
Rails.application.routes.draw do

  get 'levels/index'

  devise_for :users

  root to: "dasboard#index"
  resources :students
  resources :parents
  resources :levels
  resources :types
  resources :teachers
  resources :attendances
  resources :key_events
  resources :events
  get 'batch_action_parent' => 'parents#batch_action_parent'
  get 'check_parent_number' => 'parents#check_parent_number'
  get 'student_status' => 'students#student_status'
  get 'event_calender' => 'calendars#event_calender'
  get 'get_event_details' => 'calendars#get_event_details'

end

app/models/level.rb
class Level < ActiveRecord::Base
  serialize :days, Array

  # Associations
  has_many :LevelsStudent
  has_many :students,through: :LevelsStudent,dependent: :destroy,counter_cache: true
  has_and_belongs_to_many :users
  belongs_to :teacher
  belongs_to :user
  has_many :rewards
  has_many :attendances, :dependent => :destroy
  has_many :LevelsExam
  has_many :exams,through: :LevelsExam,dependent: :destroy,counter_cache: true

  # Validations
  validates :name, :presence =>{message: "Name can't be empty"}
  validates :name, uniqueness: true
  validates :classroom_type, :presence =>{message: "Classroom type can't be empty"}
  validates :days, :presence =>{message: "Days can't be empty"}

end

app/controllers/levels_controller.rb
class LevelsController < ApplicationController

  include LevelsHelper
  include FormHelper
  require 'will_paginate/array'

  skip_before_action :verify_authenticity_token, :only => [:destroy]
  before_action :find_level, only: [:show, :edit,:update,:destroy]

  def index
    if request.xhr? && params[:q].present?
      filter_level_list
      @levels = @levels.paginate(:page => params[:page], :per_page => 2)
    else
      @levels = Level.paginate(:page => params[:page], :per_page => 2)
    end
    add_breadcrumb "Classrooms", levels_path
  end

  def show
    add_breadcrumb "Classrooms", levels_path
  end

  def new
    @level = Level.new
  end

  def edit;end

  def create
    @level = Level.new(level_params)
    if @level.save
      flash[:notice] = "Classroom created successfully"
      redirect_to levels_path
    else
      render 'new'
    end
  end

  def update
    @level.update(level_params)
    flash[:notice] = "Classroom updated successfully"
    redirect_to level_path
  end

  def destroy
   @level.destroy
   redirect_to levels_path
  end

  private

  def find_level
    @level = Level.find(params[:id])
  end

  def level_params
    params.require(:level).permit(:name, :description, :teacher_id, :user_id, :classroom_type, {days: []})
  end

end

app/helpers/levels_helper.rb
module LevelsHelper

  # Filter dropdowns
  def level_filter
    [
      ['Contains','contain'],
      ['Equals','equals'],
      ['Starts with','start_with'],
      ['Ends with','end_with']
    ]

  end

  # Batch action method
  def level_batch_action
    [
      ['Batch Action',''],
      ['Delete','delete_selected'],
      ['Email Parent Selected','Email_parent'],

    ]
  end

  # Filter method
  def filter_level_list
    if params[:q].present?
      count = 0
      query_array = []
      query = ""
      if params[:name].present?
        if params[:q][:name_contains] == "contain"
          count = count + 1
          query += " name like ? "
          query_array << "%#{params[:name]}%"
        elsif params[:q][:name_contains] == "equals"
          count = count + 1
          query += " name = ? "
          query_array << params[:name]

        elsif params[:q][:name_contains] == "start_with"
          count = count + 1
          query += " name LIKE ? "
          query_array << "#{params[:name]}%"
        elsif params[:q][:name_contains] == "end_with"
          count = count + 1
          query += " name LIKE ? "
          query_array << "%#{params[:name]}"
        end
      end
      if count > 0 && params[:description].present?
        if params[:q][:description_contains] == "contain"
          query += " AND description like ? "
          query_array << "%#{params[:description]}%"
        elsif params[:q][:description_contains] == "equals"
          query += " AND description = ? "
          query_array << params[:description]
        elsif params[:q][:description_contains] == "start_with"
          query += " AND description like ? "
          query_array << "#{params[:description]}%"
        elsif params[:q][:description_contains] == "end_with"
          query += " AND description like ? "
          query_array << "%#{params[:description]}"
        end
      elsif params[:description].present?
        if params[:q][:description_contains] == "contain"
          query += " description like ? "
          query_array << "%#{params[:description]}%"
        elsif params[:q][:description_contains] == "equals"
          query += " description = ? "
          query_array << params[:description]
        elsif params[:q][:description_contains] == "start_with"
          query += " description like ? "
          query_array << "#{params[:description]}%"
        elsif params[:q][:description_contains] == "end_with"
          query += " description like ? "
          query_array << "%#{params[:description]}"
        end
      end
      if count > 0 && params[:classroom_type].present?
        query += " AND classroom_type = ? "
        query_array << params[:classroom_type]
      elsif params[:classroom_type].present?
        query += " classroom_type = ? "
        query_array << params[:classroom_type]
      end
      full_query = query_array.unshift(query)
      @levels = Level.where(full_query)
      @ids = @levels.collect(&:id)
      if full_query == [""]
        return @levels
      end
    else
    end
  end

end

app/views/levels/_classroom_list.html.erb
<% unless @levels.blank? %>
  <div class="table-responsive">
    <table class="table table-bordered table-striped table-hover" id="table-ext-3">
      <thead>
        <th data-check-all>
          <div class="checkbox c-checkbox" data-toggle="tooltip" data-title="Check All">
            <label>
            <input type="checkbox" name = level_arr1[] value="<%=@levels.ids%>" class="check_box_selection" id="level_main_checkbox" >
            <span class="fa fa-check"></span>
            </label>
          </div>
        </th>
        <th>Name</th>
        <th>Description</th>
        <th>Type</th>
        <th>Teacher</th>
        <th>Count</th>
        <th>Actions</th>
      </thead>
      <tbody>
        <% @levels.order('created_at DESC').each do |level|%>
          <tr>
            <td>
              <div class="checkbox c-checkbox">
                <label>
                  <input type="checkbox" name = level_arr[] value="<%=level.id%>" id ="level_check_box">
                  <span class="fa fa-check"></span>
                </label>
              </div>
            </td>
            <td><%=link_to "#{level.name}",level_path(level.id)%></td>
            <td><%= level.description%></td>
            <td><%= level.classroom_type%></td>
            <td><%= level.teacher_id%></td>
            <td><%= level.students.count%></td>
            <td>
              <div class="btn-group">
                <button class="btn btn-primary" type="button"><span class="fa fa-cog"></span></button>
                <button class="btn dropdown-toggle btn-primary" type="button" data-toggle="dropdown">
                <span class="sr-only">primary</span>
                </button>
                <div class="dropdown-menu animated" role="menu">
                  <%= link_to 'View',level_path(level.id),class: "dropdown-item"%>
                  <%= link_to 'Edit',edit_level_path(level.id),class: "dropdown-item"%>
                  <%= hidden_field_tag :d_level, level.id %>
                  <a href="JavaScript:void(0);" class= "dropdown-item swal-demo6">Delete</a>
                </div>
              </div>
            </td>
          </tr>
        <%end%>
      </tbody>
    </table>
  </div>
  <div class="pagination-link">
    <%= js_will_paginate @levels%>
  </div>
<% else %>
<p class="no_record_found">No Classroom Found</p>
<% end %>

app/views/levels/_filter_classroom.html.erb
<%= form_tag '/levels' ,method: :get,remote: true do%>
  <table class="table bb table-striped filter-table">
    <tbody>
      <tr>
        <td colspan="2">
          <label class="col-form-label">Name</label>
        </td>
      </tr>
      <tr>
        <td width="50%">
          <div class="form-group">
            <%= select_tag "q[name_contains]", options_for_select(level_filter),class: "chosen-select form-control"%>
          </div>
        </td>
        <td>
          <div class="form-group">
            <%= text_field_tag 'name' ,params[:name],class: " form-control "%>
          </div>
        </td>
      </tr>
      <tr>
        <td colspan="2">
          <label class="col-form-label">Description</label>
        </td>
      </tr>
      <tr>
        <td width="50%">
          <div class="form-group">
            <%= select_tag "q[description_contains]", options_for_select(level_filter),class: "chosen-select form-control"%>
          </div>
        </td>
        <td>
          <div class="form-group">
            <%= text_field_tag 'description' ,params[:description],class: " form-control "%>
          </div>
        </td>
      </tr>
      <tr>
        <td colspan="2">
          <label class="col-form-label">Classroom Type</label>
        </td>
      </tr>
      <tr>
        <td colspan="2">
          <div class="form-group">
            <%= select_tag "classroom_type", options_for_select([nil]+Level.pluck(:classroom_type).uniq),class: "chosen-select form-control"%>
          </div>
        </td>
      </tr>
      <tr>
        <td colspan="2">
          <label class="col-form-label">Teacher</label>
        </td>
      </tr>
      <tr>
        <td colspan="2">
          <div class="form-group">
            <%= select_tag "teacher", options_for_select([nil]+Teacher.pluck(:name,:id)),class: "chosen-select form-control"%>
          </div>
        </td>
      </tr>
        <td>
          <div class="form-group">
            <%= submit_tag 'Filter',class: "btn btn-sm btn-primary", id: "filter_level_list"%>
          </div>
        </td>
        <td>
          <div>
          <%= link_to 'Clear filter', levels_path,class: "btn btn-sm btn-warning", id: "clear-level-filter" %>
          </div>
        </td>
      </tr>
    </tbody>
  </table>
<%end%>

<style type="text/css">
  .filter-table td{
    padding: 5px;
  }
  .filter-table td .form-group{
    margin-bottom: 0;
  }
  #clear-level-filter{
    margin-left: -100px;
  }
</style>

app/views/levels/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="card card-default">
      <div class="card-header">Classroom Form</div>
        <div class="card-body">
          <%= form_for @level do |f| %>
            <%= form_group_for f, :name, label: false  do %>
              <div class="form-group">
                <label>Name*</label>
                <%= f.text_field :name ,class: "form-control", placeholder: "Enter name"%>
              </div>
            <%end%>
            <div class="form-group">
              <label>Description</label>
              <%= f.text_area :description ,class: "form-control", placeholder: "Enter address"%>
            </div>
            <div class="form-group">
              <label>Teacher</label>
              <%= f.select :teacher ,Teacher.pluck(:name,:id),{prompt: 'Select Teacher'} ,class: "form-control"%>
            </div>
            <%= form_group_for f, :classroom_type, label: false  do %>
              <div class="form-group">
                <label>Classroom Type*</label>
                <%= f.select :classroom_type ,["weekdays","weekend"],{prompt: 'Select Classroom Type'} ,class: "form-control", id: "level_classroom_type"%>
              </div>
            <% end %>
            <%= form_group_for f, :days, label: false  do %>
              <div class="form-group">
                <label>Days*</label>
                <div class="form-check">
                  <% Date::DAYNAMES.each do |day|%>
                    <%= f.check_box :days, {multiple: true}, day, false %>
                    <label><%= day%></label>
                  <% end %>
                </div>
              </div>
            <% end %>
            <%= f.submit :submit, class: "btn btn-sm btn-primary"%>
            <%= link_to 'Cancel', levels_path,class: "btn btn-sm btn-warning" %>
          <% end %>
        </div>
    </div>
  </div>
</div>

app/views/levels/edit.html.erb
<div class="wrapper">
  <%= render 'layouts/header'%>
  <%= render 'layouts/left_sidebar'%>
  <%= render 'layouts/right_sidebar'%>
  <section class="section-container">
    <div class="content-wrapper">
      <div class="content-heading">
        <div>Edit Level
        </div>
      </div>
      <%= render 'form'%>
    </div>
  </section>
</div>

app/views/levels/index.html.erb
<link rel="stylesheet" href="/assets/theme_css/sweetalert/sweetalert.css">
<div class="wrapper">
  <%= render 'layouts/header'%>
  <%= render 'layouts/left_sidebar'%>
  <%= render 'layouts/right_sidebar'%>
  <section class="section-container">
    <div class="content-wrapper">
      <div class="content-heading">
        <div>
          Classrooms
          <ol class="breadcrumb breadcrumb px-0 pb-0">
            <li class="breadcrumb-item">
              <a href="/levels"><%= render_breadcrumbs :separator => ' / ' %></a>
            </li>
          </ol>
        </div>
        <div class="ml-auto">
          <%= link_to(new_level_path,class: 'btn btn-labeled btn-success mb-2') do %>
             <span class="btn-label"><i class="fa fa-plus"></i></span>New Classroom</button>
          <% end %>
        </div>
      </div>
      <div class="row ">
        <div class="col-xl-2">
          <div class="ml-auto">
            <div class="input-group float-right">
              <div class="desktop-view">
                <%= select_tag "Batch Action", options_for_select(level_batch_action),class: "custom-select",id: "level_batch",disabled: true  %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="col-xl-4 hide-on-desktop">
          <div class="card card-default">
            <div class="card-body">
              <p class="lead">Filters</p>
                <%= render 'filter_classroom'%>
            </div>
          </div>
        </div>
        <div class="mobile-view">
          <%= select_tag "Batch Action", options_for_select(level_batch_action),class: "custom-select",id: "level_batch",disabled: true  %>
        </div>
        <div class="col-xl-8">
          <div class="card card-default">
            <div id = "level_filter_table">
              <%= render 'classroom_list'%>
            </div>
          </div>
        </div>
        <div class="col-xl-4 hide-on-mobile">
          <div class="card card-default">
            <div class="card-body">
              <p class="lead">Filters</p>
                <%= render 'filter_classroom'%>
            </div>
          </div>
        </div>
      </div>
  </section>
  <%= render '/layouts/footer'%>
</div>
<script src="/assets/theme_js/sweetalert/sweetalert.min.js"></script>
<script src="/assets/theme_js/js/app.js"></script>

app/views/levels/index.js.erb
$("#level_filter_table").html("<%=j render('classroom_list', levels: @levels)%> ")

app/views/levels/new.html.erb
<div class="wrapper">
  <%= render 'layouts/header'%>
  <%= render 'layouts/left_sidebar'%>
  <%= render 'layouts/right_sidebar'%>
  <section class="section-container">
    <div class="content-wrapper">
      <div class="content-heading">
        <div>Create new classroom
        </div>
      </div>
      <%= render 'form'%>
    </div>
  </section>
</div>

app/views/levels/show.html.erb
<link rel="stylesheet" href="/assets/theme_css/sweetalert/sweetalert.css">
<div class="wrapper">
  <%= render 'layouts/header'%>
  <%= render 'layouts/left_sidebar'%>
  <%= render 'layouts/right_sidebar'%>
  <section class="section-container">
    <div class="content-wrapper">
      <div class="content-heading">
        <div>
          <%= @level.name%>
          <ol class="breadcrumb breadcrumb px-0 pb-0">
            <li class="breadcrumb-item">
               <%= render_breadcrumbs :separator => ' / ' %>
            </li>
            <li class="breadcrumb-item active"><%= @level.name%></li>
          </ol>
        </div>
        <div class="ml-auto">
          <button class="btn btn-labeled btn-danger mb-2 swal-demo6" type="button">
            <%= hidden_field_tag :d_level, @level.id %>
            <span class="btn-label"><i class="fa fa-trash-alt" ></i></span>Delete
          </button>
          <%= link_to(edit_level_path(@level.id),class: 'btn btn-labeled btn-warning mb-2') do %>
            <span class="btn-label"><i class="fa fa-pencil-alt"></i></span>Edit
          <% end %>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-4">
          <div class="card card-default">
            <div class="card-body bb">
              <p>Today's Attendance</p>
              <div class="d-flex align-items-center mb-2">
                <div class="w-100">
                  <div class="progress progress-xs m-0">
                    <div class="progress-bar bg-info" style="width:48%"></div>
                  </div>
                </div>
                <div class="ml-auto col wd-xxs text-right">
                  <div class="text-bold text-muted">48%</div>
                </div>
              </div>
            </div>
            <div class="card-body">
              <p>Metrics</p>
              <div class="row text-center">
                <div class="col-3 col-lg-6 col-xl-3">
                  <div class="inline my-2"> <%= pie_chart @level.students.group(:gender).count,width: "70px", height: "70px",legend: false %></div>
                  <p class="mt-3">Gender</p>
                </div>
                <div class="col-3 col-lg-6 col-xl-3">
                  <div class="inline my-2"> <%= pie_chart @level.students.group(:ethnicity_group).count,width: "70px", height: "70px",legend: false,id: "ethnicity_chart" %></div>
                  <p class="mt-3">Ethinicity</p>
                </div>
              </div>
            </div>
            <table class="table bb">
              <tbody>
                <tr>
                  <td>
                    <strong>Descripition</strong>
                  </td>
                  <td><%= @level.description%></td>
                </tr>
                <tr>
                  <td>
                    <strong>Classroom Type</strong>
                  </td>
                  <td><%= @level.classroom_type%></td>
                </tr>
                <tr>
                  <td>
                    <strong>Day's Configured</strong>
                  </td>
                  <td><%= @level.days.map(&:inspect).join(', ') %></td>
                </tr>
                <tr>
                  <td>
                    <strong>Teacher</strong>
                  </td>
                  <td><%= @level.teacher%></td>
                </tr>
                <tr>
                  <td>
                    <strong>Created at</strong>
                  </td>
                  <td><%= @level.created_at.strftime('%d %B,%Y') %></td>
                </tr>
              </tbody>
            </table>
            <div class="card-footer">
              <% diff = (Time.now.to_i - @level.updated_at.to_i) %>
              <div class="text-sm text-muted">Last updated at <%= distance_of_time_in_words(diff).split("and")[0].chomp(', ') %></div>
            </div>
          </div>
        </div>
        <div class="col-lg-8">
          <div class="mb-3 d-flex">
            <div>
              <button class="btn btn-sm btn-secondary" title="Add Student to this classroom" type="button">
              <em class="fa fa-user-plus"></em>
              </button>
              <button class="btn btn-sm btn-secondary" title="Edit Classroom" type="button">
              <em class="fas fa-pencil-alt"></em>
              </button>
              <button class="btn btn-sm btn-secondary" title="Print" type="button">
              <em class="fas fa-share"></em>
              </button>
              <button class="btn btn-sm btn-secondary" title="Print Student List" type="button">
              <em class="fa fa-print"></em>
              </button>
              <button class="btn btn-sm btn-secondary" title="Delete Level" type="button">
              <em class="fa fa-trash"></em>
              </button>
            </div>
            <div class="ml-auto">
              <p class="mb-0 mt-1"><%= @level.students.count%></p>
            </div>
          </div>
          <div class="card b">
            <div class="card-body">
              <table class="table w-100" id="datatable13">
                <thead>
                  <tr>
                    <th>Student Name</th>
                    <th>Student Type</th>
                    <th>Status</th>
                    <th>fee</th>
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  <% @level.students.each do |student| %>
                    <tr>
                      <td><%=link_to "#{student.name}",student_path(student.id)%></td>
                      <td>
                        <%if student.type_id.present? && student.status == "Enrolled"%>
                          <%= Type.find(student.type_id).name %>
                        <% end %>
                      </td>
                      <td>
                        <button class="mb-1 btn btn-success" type="button"><%= student.status %></button>
                      </td>
                      <td>£<%= student.outstanding_fee %></td>
                      <td>
                        <div class="btn-group">
                          <button class="btn btn-primary" type="button"><span class="fa fa-cog"></span></button>
                          <button class="btn dropdown-toggle btn-primary" type="button" data-toggle="dropdown">
                          <span class="sr-only">primary</span>
                          </button>
                          <div class="dropdown-menu animated" role="menu">
                            <%= link_to 'View',student_path(student.id),class: "dropdown-item"%>
                            <%= link_to 'Edit',edit_student_path(student.id),class: "dropdown-item"%>
                            <%= hidden_field_tag :d_student, student.id%>
                            <a href="JavaScript:void(0);" class= "dropdown-item swal-demo7">Delete</a>
                          </div>
                        </div>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <%= render '/layouts/footer'%>
</div>
<script src="/assets/theme_js/sweetalert/sweetalert.min.js"></script>
<script src="/assets/theme_js/js/app.js"></script>