config/routes.rb
Rails.application.routes.draw do

  get 'levels/index'

  devise_for :users

  root to: "dasboard#index"
  resources :students
  resources :parents
  resources :levels
  resources :types
  resources :teachers
  resources :attendances
  resources :key_events
  resources :events
  get 'batch_action_parent' => 'parents#batch_action_parent'
  get 'check_parent_number' => 'parents#check_parent_number'
  get 'student_status' => 'students#student_status'
  get 'event_calender' => 'calendars#event_calender'
  get 'get_event_details' => 'calendars#get_event_details'

end

app/models/exam.rb
class Exam < ActiveRecord::Base
  has_many :ExamsCategory
  has_many :categories, through: :ExamsCategory, dependent: :destroy,counter_cache: true
  has_many :LevelsExam
  has_many :levels, through: :LevelsExam, dependent: :destroy,counter_cache: true
end

app/models/parent.rb
class Parent < ActiveRecord::Base
  # Associations
  belongs_to :auditlog
  has_many :students, :dependent => :destroy
  has_many :contains
  has_and_belongs_to_many :messages , join_table: :messages_parents

  # Validations
  validates :name, :presence =>{message: "Name can't be empty"}
  validates :relationship, :presence =>{message: "Relationship can't be empty"}
  validates :mobile, :presence =>{message: "Mobile can't be empty"}
  validates :mobile, uniqueness: true
  validates_associated :students

  # Nested Attributes
  accepts_nested_attributes_for :students, :allow_destroy => true

  # For Map
  geocoded_by :full_address
  after_validation :geocode, :if => :postcode_changed? and :address_changed?

  # Callbacks
  attr_accessor :notify
  before_save :capitalize_name
  after_create :send_parent_email,:fill_student_detail
  after_update :fill_student_detail

  def fill_student_detail
    if self.students.present?
      student_object_1 = self.students.where.not(emergencyno_1: nil).first
      student_object_2 = self.students.where.not(emergencyno_2: nil).first
      student_object_3 = self.students.where.not(emergencyno_3: nil).first
      self.students.all.each do |student|
        student.emergencyno_1 = student_object_1.emergencyno_1
        student.emergencyno_2 = student_object_2.emergencyno_2
        student.emergencyno_3 = student_object_3.emergencyno_3
        student.save
      end
    end
  end

  def self.check_string(string)
    string.scan(/\D/).empty?
  end

  def full_address
    [address, city, postcode].compact.join(', ')
  end

  def send_parent_email
    if self.notify == 'true' && self.email.present?
      ParentMailer.welcome_email(self).deliver_now
    end
  end

  # Country Selection
  UK_OPTION = {
    "United Kingdom" => "GB",
    "Ireland" => "IE",
  }

  IE_OPTION = {
    "Ireland" => "IE",
    "United Kingdom" => "GB",
  }

  # For capitalize parent name
  def capitalize_name
    self.name = self.name.split.collect(&:capitalize).join(' ') if self.name && !self.name.blank?
  end

end

app/controllers/parents_controller.rb
class ParentsController < ApplicationController
  include ParentsHelper
  include FormHelper
  require 'will_paginate/array'
  skip_before_action :verify_authenticity_token, :only => [:destroy]
  before_action :find_parent, only: [:show, :edit,:update,:destroy]

  def index
    if request.xhr? && params[:q].present?
      filter_parent
    else
      @parents = Parent.paginate(:page => params[:page], :per_page => 10)
    end
    add_breadcrumb "Parents", parents_path
  end


  def show
    add_breadcrumb "Parents", parents_path
  end

  def new
    @parent = Parent.new
  end

  def edit;end

  def create
    count = 0
    more_count = 0
    @parent = Parent.new(parent_params)
    if params[:parent][:students_attributes].present?
      params[:parent][:students_attributes].each do |student|
        if student.to_a.last[:dd_student] == "1"
         unless student.to_a.last[:dd_amount].present? && student.to_a.last[:dd_start_date].present?
            count = 1
            break
         end
       end
     end
   else
    more_count = 1
   end
   count.eql?(1) || !@parent.save ?  render('new') : redirect_to(parents_path)
   count.eql?(1) ? flash[:alert] = "Please fill dd_amount and dd_start_date" : @parent.save ? flash[:notice] = "Parent created successfully" : nil
  end

  def update
    @parent.update(parent_params)
    flash[:notice] = "Parent updated successfully"
    redirect_to parent_path
  end

  def destroy
    @parent.destroy
    redirect_to parents_path
  end

  def batch_action_parent
    if params[:batch_action] == "delete_selected"
      params[:batch_arr].each do |value|
        @parent = Parent.find(value)
        @parent.delete
      end
    end
  end

  def check_parent_number
    @available = Parent.pluck(:mobile).include?(params[:mobile_number])
    respond_to do |format|
      format.js
    end
  end

  private

  def find_parent
    @parent = Parent.find_by_id(params[:id])
  end

  def parent_params
    params.require(:parent).permit(:name, :address, :postcode, :home_phone, :mobile, :email,:notify, :relationship,:city,:country, students_attributes: [:first_name, :last_name, :dob, :address, :gender, :status, :postcode,:_destroy,:mobile, :email, :home_phone, :languages_spoken, :id,:start_date,:end_date,:ethnicity_group,:school_name,:special_needs,:specialneeds_notes,:pickup_dropoff,:is_disabled,:doctors_name,:disabilities_note,:outstanding_fee,:student_ref,:classroom,:emergencyno_1,:emergencyno_2,:emergencyno_3,:discount,:name,:p_maktab_name,:p_maktab_notes,:dd_student,:dd_amount,:dd_start_date,:dd_end_date,level_ids: []])
  end
end

app/helpers/parents_helper.rb
module ParentsHelper

  # for filter dropdown
  def filter_name
    [
      ['Contains','contain'],
      ['Equals','equals'],
      ['Starts with','start_with'],
      ['Ends with','end_with']
    ]

  end

  # Batch actions method
  def batch_action_name
    [
      ['Batch Action',''],
      ['Email Selected','email_send'],
      ['Sms Selected','sms_send'],
      ['Give Permission','give_permission'],
      ['Delete Selected','delete_selected']
    ]
  end

  # For students count
  def students_count_filter
    [
      ['Equal','equal'],
      ['Greater than','greater_than'],
      ['Less than','less_than']
    ]

  end

  # Filter method
  def filter_parent
    if params[:q].present?
      count = 0
      query_array = []
      query = ""
      if params[:name].present?
        if params[:q][:name_contains] == "contain"
          count = count + 1
          query += " name like ? "
          query_array << "%#{params[:name]}%"
        elsif params[:q][:name_contains] == "equals"
          count = count + 1
          query += " name = ? "
          query_array << params[:name]

        elsif params[:q][:name_contains] == "start_with"
          count = count + 1
          query += " name LIKE ? "
          query_array << "#{params[:name]}%"
        elsif params[:q][:name_contains] == "end_with"
          count = count + 1
          query += " name LIKE ? "
          query_array << "%#{params[:name]}"
        end
      end
      if count > 0 && params[:mobile].present?
        if params[:q][:mobile_contains] == "contain"
          if Parent.check_string(params[:mobile])
            query += " AND mobile like ? "
            query_array << "%#{params[:mobile]}%"
          end
        elsif params[:q][:mobile_contains] == "equals"
          if Parent.check_string(params[:mobile])
            query += " AND mobile = ? "
            query_array << params[:mobile]
          end
        elsif params[:q][:mobile_contains] == "start_with"
          if Parent.check_string(params[:mobile])
            query += " AND mobile like ? "
            query_array << "#{params[:mobile]}%"
          end
        elsif params[:q][:mobile_contains] == "end_with"
          if Parent.check_string(params[:mobile])
            query += " AND mobile like ? "
            query_array << "%#{params[:mobile]}"
          end
        end
      elsif params[:mobile].present?
        if params[:q][:mobile_contains] == "contain"
          if Parent.check_string(params[:mobile])
            query += " mobile like ? "
            query_array << "%#{params[:mobile]}%"
          end
        elsif params[:q][:mobile_contains] == "equals"
          if Parent.check_string(params[:mobile])
            query += " mobile = ? "
            query_array << params[:mobile]
          end
        elsif params[:q][:mobile_contains] == "start_with"
          if Parent.check_string(params[:mobile])
            query += " mobile like ? "
            query_array << "#{params[:mobile]}%"
          end
        elsif params[:q][:mobile_contains] == "end_with"
          if Parent.check_string(params[:mobile])
            query += " mobile like ? "
            query_array << "%#{params[:mobile]}"
          end
        end
      end
      if count > 0 && params[:postcode].present?
        if params[:q][:postcode_contains] == "contain"
          if Parent.check_string(params[:mobile])
            query += " AND postcode like ? "
            query_array << "%#{params[:postcode]}%"
          end
        elsif params[:q][:postcode_contains] == "equals"
          if Parent.check_string(params[:postcode])
            query += " AND postcode = ? "
            query_array << params[:postcode]
          end
        elsif params[:q][:postcode_contains] == "start_with"
          if Parent.check_string(params[:postcode])
            query += " AND postcode like ? "
            query_array << "#{params[:postcode]}%"
          end
        elsif params[:q][:postcode_contains] == "end_with"
          if Parent.check_string(params[:postcode])
            query += " AND postcode like ? "
            query_array << "%#{params[:postcode]}"
          end
        end
      elsif params[:postcode].present?
        if params[:q][:postcode_contains] == "contain"
          if Parent.check_string(params[:mobile])
            query += " postcode like ? "
            query_array << "%#{params[:postcode]}%"
          end
        elsif params[:q][:postcode_contains] == "equals"
          if Parent.check_string(params[:postcode])
            query += " postcode = ? "
            query_array << params[:postcode]
          end
        elsif params[:q][:postcode_contains] == "start_with"
          if Parent.check_string(params[:postcode])
            query += " postcode like ? "
            query_array << "#{params[:postcode]}%"
          end
        elsif params[:q][:postcode_contains] == "end_with"
          if Parent.check_string(params[:postcode])
            query += " postcode like ? "
            query_array << "%#{params[:postcode]}"
          end
        end
      end
      if count > 0 && params[:home_phone].present?
        if params[:q][:home_phone_contains] == "contain"
          if Parent.check_string(params[:home_phone])
            query += " AND home_phone like ? "
            query_array << "%#{params[:home_phone]}%"
          end
        elsif params[:q][:home_phone_contains] == "equals"
          if Parent.check_string(params[:home_phone])
            query += " AND home_phone = ? "
            query_array << params[:home_phone]
          end
        elsif params[:q][:home_phone_contains] == "start_with"
          if Parent.check_string(params[:home_phone])
            query += " AND home_phone like ? "
            query_array << "#{params[:home_phone]}%"
          end
        elsif params[:q][:home_phone_contains] == "end_with"
          if Parent.check_string(params[:home_phone])
            query += " AND home_phone like ? "
            query_array << "%#{params[:home_phone]}"
          end
        end
      elsif params[:home_phone].present?
        if params[:q][:home_phone_contains] == "contain"
          if Parent.check_string(params[:home_phone])
            query += " home_phone like ? "
            query_array << "%#{params[:home_phone]}%"
          end
        elsif params[:q][:home_phone_contains] == "equals"
          if Parent.check_string(params[:home_phone])
            query += " home_phone = ? "
            query_array << params[:home_phone]
          end
        elsif params[:q][:home_phone_contains] == "start_with"
          if Parent.check_string(params[:home_phone])
            query += " home_phone like ? "
            query_array << "#{params[:home_phone]}%"
          end
        elsif params[:q][:home_phone_contains] == "end_with"
          if Parent.check_string(params[:home_phone])
            query += " home_phone like ? "
            query_array << "%#{params[:home_phone]}"
          end
        end
      end
      if count > 0 && params[:email].present?
        if params[:q][:email_contains] == "contain"
          query += " AND email like ? "
          query_array << "%#{params[:email]}%"
        elsif params[:q][:email_contains] == "equals"
          query += " AND email = ? "
          query_array << params[:email]
        elsif params[:q][:email_contains] == "start_with"
          query += " AND email like ? "
          query_array << "#{params[:email]}%"
        elsif params[:q][:email_contains] == "end_with"
          query += " AND email like ? "
          query_array << "%#{params[:email]}"
        end
      elsif params[:email].present?
        if params[:q][:email_contains] == "contain"
          query += " email like ? "
          query_array << "%#{params[:email]}%"
        elsif params[:q][:email_contains] == "equals"
          query += " email = ? "
          query_array << params[:email]
        elsif params[:q][:email_contains] == "start_with"
          query += " email like ? "
          query_array << "#{params[:email]}%"
        elsif params[:q][:email_contains] == "end_with"
          query += " email like ? "
          query_array << "%#{params[:email]}"
        end
      end
      if count > 0 && params[:city].present?
        if params[:q][:city_contains] == "contain"
          query += " AND city like ? "
          query_array << "%#{params[:city]}%"
        elsif params[:q][:city_contains] == "equals"
          query += " AND city = ? "
          query_array << params[:city]
        elsif params[:q][:city_contains] == "start_with"
          query += " AND city like ? "
          query_array << "#{params[:city]}%"
        elsif params[:q][:city_contains] == "end_with"
          query += " AND city like ? "
          query_array << "%#{params[:city]}"
        end
      elsif params[:city].present?
        if params[:q][:city_contains] == "contain"
          query += " city like ? "
          query_array << "%#{params[:city]}%"
        elsif params[:q][:city_contains] == "equals"
          query += " city = ? "
          query_array << params[:city]
        elsif params[:q][:city_contains] == "start_with"
          query += " city like ? "
          query_array << "#{params[:city]}%"
        elsif params[:q][:city_contains] == "end_with"
          query += " city like ? "
          query_array << "%#{params[:city]}"
        end
      end
      if count > 0 && params[:students_count].present?
        if params[:q][:students_count_contains] == "equal"
          query += " AND students_count = ? "
          query_array << params[:students_count]
        elsif params[:q][:students_count_contains] == "greater_than"
          query += " AND students_count > ? "
          query_array << params[:students_count]
        elsif params[:q][:students_count_contains] == "less_than"
          query += " AND students_count < ? "
          query_array << params[:students_count]
        end
      elsif params[:students_count].present?

app/views/parents/_filter_parent_list.html.erb
<% unless @parents.blank?%>
  <div class="table-responsive">
    <table class="table table-bordered table-hover table-striped" id="table-ext-1">
      <thead>
        <th data-check-all>
          <div class="checkbox c-checkbox" data-toggle="tooltip" data-title="Check All" >
            <label>
            <input type="checkbox" name = parent_arr1[] value="<%=@parents.ids%>" class="check_box_selection" id="main_checkbox" >
            <span class="fa fa-check"></span>
            </label>
          </div>
        </th>
        <th>Name</th>
        <th>Mobile</th>
        <th>Email</th>
        <th>Count</th>
        <th>Fee</th>
        <th>Actions</th>
      </thead>
      <tbody>
        <% @parents.order('created_at DESC').each do |parent|%>
          <tr>
            <td>
              <div class="checkbox c-checkbox">
                <label>
                <input type="checkbox" name = parent_arr[] value="<%=parent.id%>" id="check_box_selection">
                <span class="fa fa-check"></span>
                </label>
              </div>
            </td>
            <td><%=link_to "#{parent.name}",parent_path(parent.id)%></td>
            <td><%= parent.mobile%></td>
            <td><%= parent.email%></td>
            <td><%= parent.students_count%></td>
            <td>£<%=0.00%></td>
            <td>
              <div class="btn-group">
                <button class="btn btn-primary" type="button"><span class="fa fa-cog"></span></button>
                <button class="btn dropdown-toggle btn-primary" type="button" data-toggle="dropdown">
                <span class="sr-only">primary</span>
                </button>
                <div class="dropdown-menu" role="menu">
                  <%= link_to 'View',parent_path(parent.id),class: "dropdown-item"%>
                  <%= link_to 'Edit',edit_parent_path(parent.id),class: "dropdown-item"%>
                  <%= hidden_field_tag :d_parent, parent.id %>
                  <a href="JavaScript:void(0);" class= "dropdown-item swal-demo5">Delete</a>
                  <!-- <a href="" class="dropdown-item">Email Statement</a>
                  <a href="" class="dropdown-item">New Child</a> -->
                </div>
              </div>
            </td>
          </tr>
        <%end%>
      </tbody>
    </table>
  </div>
  <div class="pagination-link">
    <%= js_will_paginate @parents%>
  </div>
<% else%>
  <p class="no_record_found">No Parent Found</p>
<% end %>

app/views/parents/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="card card-default">
      <div class="card-header">Parent Form</div>
        <div class="card-body">
          <%= nested_form_for @parent do |f| %>
            <%= form_group_for f, :name, label: false  do %>
              <div class="form-group">
                <label>Name*</label>
                <%= f.text_field :name ,class: "form-control", placeholder: "Enter name"%>
              </div>
            <%end%>
            <div class="form-group">
              <label>Address</label>
              <%= f.text_field :address ,class: "form-control", placeholder: "Enter address"%>
            </div>
            <div class=" form-group">
              <label>Postcode</label>
              <%= f.text_field :postcode,class: "form-control",placeholder: "Enter address"%>
            </div>
            <div class="form-group">
              <label>Country</label>
              <%= f.select :country ,options_for_select(Parent::UK_OPTION),{prompt: 'Select Country'} ,class: "form-control"%>
            </div>
            <div class="form-group">
              <label>City</label>
              <%= f.text_field :city ,class: "form-control", placeholder: "Enter city"%>
            </div>
            <div class="form-group">
              <label>Home Phone</label>
              <%= f.text_field :home_phone,class: "form-control",placeholder: "Enter home phone"%>
            </div>
            <%= form_group_for f, :mobile, label: false  do %>
              <div class="form-group">
                <label>Mobile*</label>
                <%= f.text_field :mobile ,class: "form-control", placeholder: "Enter mobile"%>
                <p class="inline-hints"></p>
              </div>
            <%end%>
            <div class="form-group">
              <label>Email</label>
              <%= f.text_field :email ,class: "form-control", placeholder: "Enter mobile"%>
            </div>
            <%= form_group_for f, :relationship, label: false  do %>
              <div class="form-group">
                <label >Relationship*</label>
                <%= f.select :relationship,['Mother','Father'],{prompt: 'Select Relationship'} ,class: "form-control"%>
              </div>
            <%end%>
            <label >Notify (If yes an email will be sent to the parent.)</label><br>
            <div class="form-check form-check-inline">
              <%= f.radio_button :notify,true ,class: "form-check-input"%>
              <label class="form-check-label" for="inlineRadio1">Yes</label>
            </div>
            <div class="form-check form-check-inline">
             <%= f.radio_button :notify,false ,class: "form-check-input"%>
              <label class="form-check-label" for="inlineRadio2">No</label>
            </div><br><br>
            <%unless @parent.persisted?%>
              <h3>Student Form</h3>
                <%= f.fields_for :students do |s|%>
                  <%= render 'student_form',s: s%>
                <%end%>
              <div class="form-group">
                <%= f.link_to_add 'Add Student',:students,class: "btn btn-sm btn-primary"%>
              </div>
            <%end%>
            <%= f.submit :submit, class: "btn btn-sm btn-primary"%>
            <%= link_to 'Cancel', parents_path,class: "btn btn-sm btn-warning" %>
          <% end %>
        </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(document).on('blur', '#parent_mobile', function() {
    var mobile_number;
    mobile_number = $(this).val();
    $.ajax({
      url: '/check_parent_number.js',
      data: {
        mobile_number: mobile_number
      },
      type: 'get',
      success: function(data) {}
    });
  });
</script>

app/views/parents/index.html.erb
<link rel="stylesheet" href="/assets/theme_css/sweetalert/sweetalert.css">
<div class="wrapper">
  <%= render 'layouts/header'%>
  <%= render 'layouts/left_sidebar'%>
  <%= render 'layouts/right_sidebar'%>
  <section class="section-container">
    <div class="content-wrapper">
      <div class="content-heading">
        <div>
          Parents
          <ol class="breadcrumb breadcrumb px-0 pb-0">
            <li class="breadcrumb-item active">
              <a href="/parents"><%= render_breadcrumbs :separator => ' / ' %></a>
            </li>
          </ol>
        </div>
        <div class="ml-auto">
          <%= link_to(new_parent_path,class: 'btn btn-labeled btn-success mb-2') do %>
              <span class="btn-label"><i class="fa fa-plus"></i></span>New Parent
          <% end %>
          <a class="btn btn-labeled btn-primary mb-2" href="import.html"><span class="btn-label"><i class="fa fa-upload"></i></span>Import Parents</a>
        </div>
      </div>
      <div class="row">
        <div class="col-xl-2">
          <div class="ml-auto">
            <div class="input-group float-right">
              <div class="desktop-view">
                <%= select_tag "Batch Action", options_for_select(batch_action_name),class: "custom-select",id: "batch_action_kind", disabled: true %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <br/>
      <div class="row">
        <div class="col-xl-4 hide-on-desktop">
          <div class="card card-default">
            <div class="card-body">
              <p class="lead">Filters</p>
              <%= render 'filter_table'%>
            </div>
          </div>
        </div>
        <div class="mobile-view">
          <%= select_tag "Batch Action", options_for_select(batch_action_name),class: "custom-select",id: "batch_action_kind", disabled: true %>
        </div>
        <div class="col-xl-8">
          <div class="card card-default">
            <div id = "parent_filter_table">
              <%= render 'filter_parent_list'%>
            </div>
          </div>
        </div>
        <div class="col-xl-4 hide-on-mobile">
          <div class="card card-default">
            <div class="card-body">
              <p class="lead">Filters</p>
              <%= render 'filter_table'%>
            </div>
          </div>
        </div>
      </div>
  </section>
  <%= render '/layouts/footer'%>
</div>

<script src="/assets/theme_js/sweetalert/sweetalert.min.js"></script>
<script src="/assets/theme_js/js/app.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>

app/views/parents/show.html.erb
<link rel="stylesheet" href="/assets/theme_css/sweetalert/sweetalert.css">
<div class="wrapper">
  <%= render 'layouts/header'%>
  <%= render 'layouts/left_sidebar'%>
  <%= render 'layouts/right_sidebar'%>
  <section class="section-container">
    <div class="content-wrapper">
      <div class="content-heading">
        <div>
          <%= @parent.name %>
          <ol class="breadcrumb breadcrumb px-0 pb-0">
            <li class="breadcrumb-item">
              <%= render_breadcrumbs :separator => ' / ' %>
            </li>
            <li class="breadcrumb-item active"><%=@parent.name%></li>
          </ol>
        </div>
        <div class="ml-auto">
          <button class="btn btn-labeled btn-danger mb-2 swal-demo5" type="button">
            <%= hidden_field_tag :d_parent, @parent.id %>
            <span class="btn-label"><i class="fa fa-trash-alt" ></i></span>Delete
          </button>
          <%= link_to(edit_parent_path(@parent.id),class: 'btn btn-labeled btn-warning mb-2') do %>
            <span class="btn-label"><i class="fa fa-pencil-alt"></i></span>Edit
          <% end %>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-4">
          <div class="card card-default">
            <div class="card-body bb text-center">
              <div class="py-4">
                <img class="img-fluid rounded-circle img-thumbnail thumb96" src="/assets/user/02.jpeg" alt="Contact">
              </div>
            </div>
            <table class="table bb table-striped">
              <tbody>
                <tr>
                  <td>
                    <strong>Address</strong>
                  </td>
                  <td><%= @parent.address%></td>
                </tr>
                <tr>
                  <td>
                    <strong>City</strong>
                  </td>
                  <td><%= @parent.city%></td>
                </tr>
                <tr>
                  <td>
                    <strong>Country</strong>
                  </td>
                  <td><%= @parent.country%></td>
                </tr>
                <tr>
                  <td>
                    <strong>Postcode</strong>
                  </td>
                  <td><%= @parent.postcode%></td>
                </tr>
                <tr>
                  <td>
                    <strong>Mobile</strong>
                  </td>
                  <td><%= @parent.mobile%></td>
                </tr>
                <tr>
                  <td>
                    <strong>Home Phone</strong>
                  </td>
                  <td><%= @parent.home_phone%></td>
                </tr>
                <tr>
                  <td>
                    <strong>Email</strong>
                  </td>
                  <td><%= @parent.email%></td>
                </tr>
                <tr>
                  <td>
                    <strong>Map</strong>
                  </td>
                  <%if @parent.latitude.present? && @parent.longitude.present?%>
                    <td><%= image_tag("https://maps.googleapis.com/maps/api/staticmap?center=#{@parent.postcode}&zoom=16&size=600x300&maptype=roadmap&markers=color:green%7Clabel:P%7C#{@parent.latitude},#{@parent.longitude}&key=AIzaSyAZoiN-C9hunzDJaXKCp_y6EvcvRlxIn1I")%></td>
                  <%else%>
                    <td> NO MAP AVAILABLE</td>
                  <%end%>
                </tr>
                <tr>
                  <td>
                    <strong>Created at</strong>
                  </td>
                  <td><%= @parent.created_at.strftime('%d %B,%Y')%></td>
                </tr>
              </tbody>
            </table>
            <div class="card-footer">
              <% diff = (Time.now.to_i - @parent.updated_at.to_i) %>
              <div class="text-sm text-muted">Last updated at <%= distance_of_time_in_words(diff).split("and")[0].chomp(', ') %></div>
            </div>
          </div>
        </div>
        <div class="col-lg-8">
          <div class="mb-3 d-flex">
            <div>
              <button class="btn btn-sm btn-secondary" type="button" data-toggle="tooltip" data-title="Add New Student">
              <em class="fa fa-user-plus"></em>
              </button>
              <button class="btn btn-sm btn-secondary" type="button" data-toggle="tooltip" data-title="Print Student List">
              <em class="fa fa-print"></em>
              </button>
              <button class="btn btn-sm btn-secondary" type="button" data-toggle="tooltip" data-title="Log Payment">
              <em class="fa fa-pound-sign"></em>
              </button>
              <button class="btn btn-sm btn-secondary" type="button" data-toggle="tooltip" data-title="Send SMS">
              <em class="fa fa-mobile-alt"></em>
              </button>
            </div>
            <div class="ml-auto"></div>
          </div>
          <div class="card b">
            <div class="card-body">
              <table class="table w-100 table-striped " id="datatable1">
                <thead>
                  <tr>
                    <th>Student Name</th>
                    <th>Classroom</th>
                    <th>Student Type</th>
                    <th>Status</th>
                    <th>fee</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                  <% @parent.students.each do |student|%>
                    <tr>
                      <td>
                        <%= link_to "#{student.name}", student_path(student.id) %>
                      </td>
                      <td><%= student.classroom%></td>
                      <td>
                        <%if student.type_id.present? && student.status == "Enrolled"%>
                          <%= Type.find(student.type_id).name %>
                        <% end %>
                        </td>
                      <td>
                        <%= student.status%>
                      </td>
                      <td>£<%= student.outstanding_fee%></td>
                      <td>
                        <div class="btn-group">
                          <button class="btn btn-primary" type="button"><span class="fa fa-cog"></span></button>
                          <button class="btn dropdown-toggle btn-primary" type="button" data-toggle="dropdown">
                          <span class="sr-only">primary</span>
                          </button>
                          <div class="dropdown-menu" role="menu">
                            <%= link_to 'View',student_path(student.id),class: "dropdown-item"%>
                            <%= link_to 'Edit',edit_student_path(student.id),class: "dropdown-item"%>
                            <%= hidden_field_tag :d_student, student.id%>
                            <a href="JavaScript:void(0);" class= "dropdown-item swal-demo7">Delete</a>
                          </div>
                        </div>
                      </td>
                    </tr>
                  <%end%>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <%= render '/layouts/footer'%>
</div>
<script src="/assets/theme_js/sweetalert/sweetalert.min.js"></script>
<script src="/assets/theme_js/js/app.js"></script>